/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/HelloWorld copy.vue')['default']
    Ffff: typeof import('./components/Posts.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Notification: typeof import('./components/base/notification.vue')['default']
    Posts: typeof import('./components/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VNotification: typeof import('./components/base/VNotification.vue')['default']
  }
}
